language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4

# command to install dependencies
install:
  - python python26/setup.py install
  - pip install -r requirements-dev.txt

# command to run tests
script:  python python26/setup.py test

